# Generated by Django 5.2.8 on 2025-11-09 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=5)),
                ('meaning', models.TextField()),
                ('onyomi', models.CharField(blank=True, max_length=100)),
                ('kunyomi', models.CharField(blank=True, max_length=100)),
                ('stroke_count', models.IntegerField(default=0)),
                ('stroke_order_url', models.URLField(blank=True)),
                ('jlpt_level', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('reading', models.CharField(blank=True, max_length=100)),
                ('meaning', models.TextField()),
                ('part_of_speech', models.CharField(blank=True, max_length=100)),
                ('jlpt_level', models.CharField(blank=True, max_length=10)),
                ('audio_url', models.URLField(blank=True)),
                ('example_jp', models.TextField(blank=True)),
                ('example_en', models.TextField(blank=True)),
                ('is_kanji', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('start', 'start'), ('end', 'end'), ('contain', 'contain')], max_length=10)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='words.kanji')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
    ]
